version: '3.8'

services:
  jumphost:
    image: shamimrezasohag/jump-host:latest
    container_name: jumphost
    ports:
      - "3000:3000"  # Wetty web access for SSH via browser
      - "2222:22"    # SSH access to the Jump Host
    networks:
      - jump_network
    depends_on:
      - dns-suricata
      - nginx-suricata
      - nikto-nmap

  dns-suricata:
    image: shamimrezasohag/dns-suricata-tcpdump:latest
    container_name: dns-suricata
    networks:
      - jump_network

  nginx-suricata:
    image: shamimrezasohag/nginx-suricata-tcpdump:latest
    container_name: nginx-suricata
    networks:
      - jump_network

  nikto-nmap:
    image: shamimrezasohag/nikto-nmap:latest
    container_name: nikto-nmap
    networks:
      - jump_network

networks:
  jump_network:
    driver: bridge
