version: '3'

services:
  dns-suricata-tcpdump:
    build: ./container1
    container_name: dns-suricata-tcpdump
    networks:
      - lab_net
    ports:
      - "5300:53/udp"
      - "2221:22"
  
  nginx-suricata-tcpdump:
    build: ./container2
    container_name: nginx-suricata-tcpdump
    networks:
      - lab_net
    ports:
      - "80:80"
      - "2222:22"
  
  nikto-nmap:
    build: ./container3
    container_name: nikto-nmap
    networks:
      - lab_net
    ports:
      - "2223:22"
  
  web-jump-host:
    build: ./jump_host
    container_name: web-jump-host
    networks:
      - lab_net
    ports:
      - "3000:3000"
    environment:
      - WETTY_PORT=3000

networks:
  lab_net:
    driver: bridge

